#!/bin/bash

export ATASHAREDIR="/opt/mnt"
export PATH=/home/sonata/miniconda3/bin:/opt/mnt/bin:$PATH
export LD_LIBRARY_PATH=/opt/mnt/lib:$LD_LIBRARY_PATH
# use environment variable instead of HOME/"/tmp" to ensure user-agnostic key is generated by ftok
export HASHPIPE_KEYFILE=/home/sonata

/opt/mnt/bin/init_pypeline.sh 0 1 >> /var/log/init_hpguppi_pypeline.log 2>&1

#exit 0
